osx_image: xcode10.2
dist: trusty
sudo: true
language: node_js
node_js: '10'
#cache:
#  directories:
#  - node_modules
#  - "$HOME/.cache/"
os:
  - osx
#addons:
#  apt:
#    packages:
#    - xvfb
#before_install:
#- npm update -g npm
#install:
#- export DISPLAY=':99.0'
#- Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
#- npm install
script:
  - npm run test
#  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./run_test.sh; fi'
#  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./run_build.sh; fi'
branches:
  only:
  - master
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "ElizabethMa"
  - git config --local user.email "ma_yanqiong@163.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d %H:%M:%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  - provider: releases
    api_key:
      secure: lPa90tn/Tl9wUjmmnB5XWpicKyiPKMUmqcx1Y3yFF7Ip2gRcUjAhFZFF2jeuC53pqfM2ggDVL/3+dJ7V0WOpynxKGI/m4MjbfxQmEkUCfSQCPJKMP20a7KrKNAgIwv1vDn32EROS/NpbkTTwDz7D8C4a5V6f3D9TTa5mrnNXsFnmxnhx9alhUSLVW7mzQMBa9ma5tRipUEkbgw6wqGWTvs25QpL03xHAPhWC3kK5i1BWTUDC/LTWh2/5S4Tb1qFACx7cHWRDrf21WZhn9YW7iop3AqnekHjbC4IkAJk3/RJntQCdLwDVxUUhMCn6ARWgA0pPqLEVp+OwFsAG8GiuuwjmJISbaVuPhgmbbRXmPcG8X2adjZ1e6OyX1QyC/2A7bZSXC0PYSa/4HmQHj8bpkcHMqfVujUXWOxQGvtca2dtQYNE6xUxdRN3FUoQsHu6ekRbJLmYnh7rcc9e7CrS3ue9fcLaZbtRlkRxdOcH/FnynkpOZFKnkuM+Y5Zb8/GETlN4T5b2ManpQoCtFm52d0OnIbTKxc9wpio6LpJIRt9WAvkFBFOjBq+UG0xQ91k0FYO0Uza7Bhh6CkxFAeAvrECIie1JIeIw/NGEgSRdVYNkTNo7TaLBQgazhZHMzmwjNVrKEp+se6aqPR9C8iPNVQulNezj9PafdybAwUKv2NZ8=
    file_glob: true
    file: dist_electron/*.dmg
    skip_cleanup: true
    on:
      branch: master
      repo: yanqiong/tianqin

  - provider: releases
    api_key:
      secure: lPa90tn/Tl9wUjmmnB5XWpicKyiPKMUmqcx1Y3yFF7Ip2gRcUjAhFZFF2jeuC53pqfM2ggDVL/3+dJ7V0WOpynxKGI/m4MjbfxQmEkUCfSQCPJKMP20a7KrKNAgIwv1vDn32EROS/NpbkTTwDz7D8C4a5V6f3D9TTa5mrnNXsFnmxnhx9alhUSLVW7mzQMBa9ma5tRipUEkbgw6wqGWTvs25QpL03xHAPhWC3kK5i1BWTUDC/LTWh2/5S4Tb1qFACx7cHWRDrf21WZhn9YW7iop3AqnekHjbC4IkAJk3/RJntQCdLwDVxUUhMCn6ARWgA0pPqLEVp+OwFsAG8GiuuwjmJISbaVuPhgmbbRXmPcG8X2adjZ1e6OyX1QyC/2A7bZSXC0PYSa/4HmQHj8bpkcHMqfVujUXWOxQGvtca2dtQYNE6xUxdRN3FUoQsHu6ekRbJLmYnh7rcc9e7CrS3ue9fcLaZbtRlkRxdOcH/FnynkpOZFKnkuM+Y5Zb8/GETlN4T5b2ManpQoCtFm52d0OnIbTKxc9wpio6LpJIRt9WAvkFBFOjBq+UG0xQ91k0FYO0Uza7Bhh6CkxFAeAvrECIie1JIeIw/NGEgSRdVYNkTNo7TaLBQgazhZHMzmwjNVrKEp+se6aqPR9C8iPNVQulNezj9PafdybAwUKv2NZ8=
    file_glob: true
    file: dist_electron/*.dmg
    skip_cleanup: true
    draft: true
    on:
      type: pull_request
      branch: master
      repo: yanqiong/tianqin
