osx_image: xcode10.2

dist: trusty

sudo: true

language: node_js
node_js: "10"

cache:
  directories:
  - node_modules
  - $HOME/.cache/

os:
  - linux
  - osx

addons:
  apt:
    packages:
    - xvfb

before_install:
  - npm update -g npm

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install

script:
  - npm run electron:build_all

branches:
  only:
  - master

deploy:
  provider: releases
  file: "dist_electron/*"
  skip_cleanup: true
  on:
    tags: true
